version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sipledes
      POSTGRES_USER: sipledes_user
      POSTGRES_PASSWORD: sipledes_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: